### ISSUE TITLE
List all domains

### ISSUE THREAD

**Issue by forteller** [NewAlexandria/awesome-browser-containers#2]
Thank you for creating this list of containers, and the extended version of some containers!

This is a request for those extended versions. You say the point is to add more domains, but there's no list of which domains that is. And when the original Facebook and Google container extensions has been updated much more recently than your versions, I'd very much appreciate the possibility of checking if they have cought up to your extended forks or not.

So I hope you can add a list to both the extensions. Thank you very much!

**Comment by NewAlexandria** [comment]
Thanks.  I just added the updates from the master, if i'll also add a list of what's been supported.

**Comment by NewAlexandria** [comment]
ok, done.  Also I added the ability to open issues on that repo - pardon that you had to post it here. 

https://github.com/NewAlexandria/contain-google/pull/3

**Comment by NewAlexandria** [comment]
It looks like they're doing something with the FB SSO buttons on the master repo of contain-facebook.  I don't think that covers the work I did on the fork, though.  I'll make updates regardless.

**Comment by forteller** [comment]
Thank you very much!

But I couldn't see a list on the Facebook container? https://github.com/NewAlexandria/contain-facebook

I'm just very uncertain about which extension I should reccommend people to use. Of course, personally I can check from time to time if you fall way behind, not updating your extensions for months while the "official" extensions does get updated. But if I tell others to install yours, they will not do the same. I hope you understand my concern that forked extensions, expecially the Fb one forked from an official extension by Mozilla, might not be keept as up to date as the originals always.

Maybe it would help me decide if you could also add a short text explaining why it's important to contain the extra domains you've added, even though it seems like they are not acutally owned by Google?

Thank you so much again! :)
